CLASS zcl_la02_bp_sales_order DEFINITION
PUBLIC
ABSTRACT
FINAL FOR BEHAVIOR OF zr_la02_sales_order.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_la02_bp_sales_order IMPLEMENTATION.
ENDCLASS.
